---
deployment:
  tasks:
    # Copy frontend to public_html
    - /bin/cp -r /home/mahakal2/repositories/mahakali-app/apps/mahakali/dist/public/* /home/mahakal2/public_html/

    # Restart Node.js app
    - touch /home/mahakal2/repositories/mahakali-app/apps/api-server/tmp/restart.txt
